### ISSUE TITLE
Missing cmake_minimum_required command in gtestdownloadCMakeLists.txt.in

### ISSUE THREAD

**Issue by GrantComm** [741g/vperfetto#17]
The gtestdownloadCMakeLists.txt.in is missing a 'cmake_minimum_required' command, which causes the build to fail.
<img width="376" alt="Screen Shot 2022-06-26 at 7 01 04 PM" src="https://user-images.githubusercontent.com/54776434/175846419-21b8efbe-0057-44f2-be45-84e8b3c455e6.png">

**Comment by zhangyiwei** [comment]
adding the `cmake_minimum_required(VERSION X.XX)` to `gtestdownloadCMakeLists.txt.in` can workaround the issue. Replace with X.XX with what's on your system
