### ISSUE TITLE
vperfetto-min loops endlessly during initialization

### ISSUE THREAD

**Issue by tomeuv** [741g/vperfetto#5]
Haven't checked why, but the loop never finishes:

https://github.com/741g/vperfetto/blob/8aa7d0ddbcfbd936250c0bae654d7529caf9c205/vperfetto-min.cpp#L96-L106

If I comment that loop out, things seem to work just fine.

**Comment by 741g** [comment]
So that assumes the tracing daemon for the system has already been started. I guess it's fine to comment it out as in real use cases tracing should live long enough for that acknowledgement latency to not be a problem.

**Comment by 741g** [comment]
Removed in https://github.com/741g/vperfetto/commit/3ce4813ae114e5f2e6e0b3f29517a88246c00363
